# http://docs.travis-ci.com/user/build-configuration/

language: python

python:
    - "3.4"

sudo: required

services:
    - mysql

install:
    - pip install --upgrade pip
    - pip --version
    - pip install Flask
    - pip install Flask-Script
    - pip install Flask-SQLAlchemy
    - pip3 install flask-googlemaps
    - pip3 install sqlalchemy_utils

before_script:
    - uname -a
    - printenv
    - pip list
    - mysql -u root -e 'create database myapp_test;'

script:
    - date
    - ls -al
    - make IDB1.log
    - ls -al
    - make check
    - ls -al
    - make test
