FORMAT: 1A
HOST: http://sweography.me

# Internet Country Database API

Internet Country Database gives you information about countries and their relating regions, currencies, and languages.

## Countries Collection -- /country [/country{?id,region_id,currency_id,language_id}]

### List Countries [GET]

+ Parameters
    + id (optional, integer)
        Response contains the country with the specified id
    + region_id (optional, integer)
        Response contains only countries in the specified region
    + currency_id (optional, integer)
        Response contains only countries that use the specified currency
    + language_id (optional, integer)
        Response contains only countries who speak the specified language

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "United States of America",
                "lat": 38,
                "lng": -97,
                "region": "Americas",
                "subregion": "North America",
                "population": 321645000,
                "area": 1000,
                "capital": "Washington, DC",
                "languages": [
                    "en"
                ],
                "currencies": [
                    "USD",
                    "USN",
                    "USS"
                ],
                "borders": [
                    "CAN",
                    "MEX"
                ]
            }
        ]

### Create a New Country [POST]


+ Request (application/json)

        {
            "name": "United States of America",
            "lat": 38,
            "lng": -97,
            "region": "Americas",
            "subregion": "North America",
            "population": 321645000,
            "area": 1000,
            "capital": "Washington, DC",
            "languages": [
                "en"
            ],
            "currencies": [
                "USD",
                "USN",
                "USS"
            ],
            "borders": [
                "CAN",
                "MEX"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /countries/2

    + Body

               {
                    "id": 2,
                    "name": "United States of America",
                    "lat": 38,
                    "lng": -97,
                    "population": 321645000,
                    "area": 1000,
                    "capital": "Washington, DC",
                    "subregion": "North America",
                    "region": "Americas",
                    "languages": [
                        "en"
                    ],
                    "currencies": [
                        "USD",
                        "USN",
                        "USS"
                    ],
                    "borders": [
                        "CAN",
                        "MEX"
                    ]
                }

## Single Country -- /country/{id} [/country/{id}]

### Get a Country [GET]

+ Response 200 (application/json)


        {
            "id": 1,
            "name": "United States of America",
            "lat": 38,
            "lng": -97,
            "region": "Americas",
            "subregion": "North America",
            "population": 321645000,
            "area": 1000,
            "capital": "Washington, DC",
            "languages": [
                "en"
            ],
            "currencies": [
                "USD",
                "USN",
                "USS"
            ],
            "borders": [
                "CAN",
                "MEX"
            ]
        }


### Update a Country [PUT]

+ Request (application/json)

        {
            "name": "United States of America",
            "lat": 38,
            "lng": -97,
            "region": "Americas",
            "subregion": "North America",
            "population": 321645000,
            "area": 1000,
            "capital": "Washington, DC",
            "languages": [
                "en"
            ],
            "currencies": [
                "USD",
                "USN",
                "USS"
            ],
            "borders": [
                "CAN",
                "MEX"
            ]
        }

+ Response 200 (application/json)

    + Headers

            Location: /country/{id}

    + Body

               {
                    "id": 2,
                    "name": "United States of America",
                    "lat": 38,
                    "lng": -97,
                    "population": 321645000,
                    "area": 1000,
                    "region": "Americas",
                    "subregion": "North America",
                    "capital": "Washington, DC",
                    "languages": [
                        "en"
                    ],
                    "currencies": [
                        "USD",
                        "USN",
                        "USS"
                    ],
                    "borders": [
                        "CAN",
                        "MEX"
                    ]
                }

### Remove a Country [DELETE]

+ Request (application/json)

+ Response 204


## Regions Collection -- /region [/region]

### List Regions [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "Americas",
                "area": 999999,
                "population": 99999,
                "subregions": 4,
                "countries": 5,
                "languages": 10,
                "currencies": 10
            },
            {
                "id": 2,
                "name": "Asia",
                "area": 999999,
                "population": 99999,
                "subregions": 4,
                "countries": 5,
                "languages": 10,
                "currencies": 10
            }
        ]

### Create a New Region [POST]

+ Request (application/json)

        {
            "name": "Americas"
        }

+ Response 201 (application/json)

    + Headers

            Location: /region/2

    + Body

               {
                    "id": 1,
                    "name": "Americas"
                }

## Single Region -- /region/{id} [/region/{id}]

### Get a Region [GET]

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "Americas",
            "area": 999999,
            "population": 99999,
            "subregions": 4,
            "countries": 5,
            "languages": 10,
            "currencies": 10
        }



### Update a Region [PUT]

+ Request (application/json)

        {
            "name": "Americas",
        }

+ Response 200 (application/json)

    + Headers

            Location: /region/{id}

    + Body

               {
                    "id": 1,
                    "name": "Americas",
                    "area": 999999,
                    "population": 99999,
                    "subregions": 4,
                    "countries": 5,
                    "languages": 10,
                    "currencies": 10
                }

### Remove a Region [DELETE]

+ Request (application/json)

+ Response 204


## Languages Collection -- /language [/language]

### List Languages [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "iso": "en",
                "name": "English",
                "countries": 2,
                "regions": 1,
                "subregion": 1
            },
            {
                "id": 2,
                "iso": "no",
                "name": "Norwegian",
                "countries": 2,
                "regions": 1,
                "subregion": 1
            }
        ]

### Create a New Language [POST]

+ Request (application/json)

        {
            "iso": "sp",
            "name": "Spanish"
        }

+ Response 201 (application/json)

    + Headers

            Location: /languages/2

    + Body

               {
                    "id": 2,
                    "iso": "sp",
                    "name": "Spanish",
                    "countries": 1,
                    "regions": 1,
                    "subregion": 1
                }

## Single Language -- /langauge/{id} [/language/{id}]

### Get a Language [GET]

+ Response 200 (application/json)

        {
            "id": 1,
            "iso": "en",
            "name": "English",
            "countries": 2,
            "regions": 1,
            "subregion": 1
        }


### Update a Language [PUT]

+ Request (application/json)

        {
            "iso": "en",
            "name": "English"
        }

+ Response 200 (application/json)

    + Headers

            Location: /language/{id}

    + Body

               {
                    "id": 1,
                    "iso": "en",
                    "name": "English",
                    "countries": 2,
                    "regions": 1,
                    "subregion": 1
                }

### Remove a Language [DELETE]

+ Request (application/json)

+ Response 204


## Currency Collection -- /currency [/currency]

### List Currencies [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "code": "USD",
                "name": "US Dollar",
                "countries": 1,
                "regions": 1,
                "subregions": 1
            },
            {
                "id": 2,
                "code": "NOR",
                "name": "Norway Kroner",
                "countries": 1,
                "regions": 1,
                "subregions": 1
            }
        ]

### Create a New Currency [POST]

+ Request (application/json)

        {
            "code": "USD",
            "name": "US Dollar"
        }

+ Response 201 (application/json)

    + Headers

            Location: /currency/2

    + Body

               {
                    "id": 2,
                    "code": "USD",
                    "name": "US Dollar",
                    "countries": 1,
                    "regions": 1,
                    "subregions": 1
                }

## Single Currency -- /currency/{id} [/currency/{id}]

### Get a Currency [GET]

+ Response 200 (application/json)

        {
            "id": 1,
            "code": "USD",
            "name": "US Dollar",
            "countries": 1,
            "regions": 1,
            "subregions": 1
        }



### Update a Currency [PUT]

+ Request (application/json)

        {
            "code": "USD",
            "name": "US Dollar"
        }

+ Response 200 (application/json)

    + Headers

            Location: /currency/{id}

    + Body

               {
                    "id": 1,
                    "name": "US Dollar",
                    "code": "USD"
                    "countries": 1,
                    "regions": 1,
                    "subregions": 1
                }

### Remove a Currency [DELETE]

+ Request (application/json)

+ Response 204


## Subregion Collection -- /subregion [/subregion]

### List Subregions [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "North America",
                "languages": 1,
                "region": "Americas",
                "countries": 1,
                "currencies": 1
            },
            {
                "id": 2,
                "name": "South America",
                "languages": 1,
                "region": "Americas",
                "countries": 1,
                "currencies": 1
            }
        ]

### Create a New Subregion [POST]

+ Request (application/json)

        {
            "name": "North America"
        }

+ Response 201 (application/json)

    + Headers

            Location: /subregion/2

    + Body

               {
                    "id": 2,
                    "name": "North America",
                    "languages": 1,
                    "region": "Americas",
                    "countries": 1,
                    "currencies": 1
                }

## Single Subregion -- /subregion/{id} [/subregion/{id}]

### Get a Subregion [GET]

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "North America",
            "languages": 1,
            "region": "Americas",
            "countries": 1,
            "currencies": 1
        }



### Update a Subregion [PUT]

+ Request (application/json)

        {
            "name": "North America"
        }

+ Response 200 (application/json)

    + Headers

            Location: /region/{id}

    + Body

               {
                    "id": 1,
                    "name": "North America",
                    "languages": 1,
                    "region": "Americas",
                    "countries": 1,
                    "currencies": 1
                }

### Remove a Subregion [DELETE]

+ Request (application/json)

+ Response 204